source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'pg'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
  # Updated version of minitest, rake test complains
  gem 'minitest', "~> 2.9"
  # Adds rspec in testing environment
  gem "rspec"
  gem "rspec-rails"
  gem "rspec-core"
  gem "rspec-expectations"
  gem "rspec-mocks"
  gem "shoulda"
  gem "fabrication" # same as factory girl
  gem "database_cleaner"
  gem "faker" # creates fake data
  gem "capybara" # for ui testing (integration tests)
end
